apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: webapp2
        image: venkatr87/webapp2:IMAGE_TAG
        ports:
        - containerPort: 8080
